#ifndef SRC_CONTROLLER_AIRFORCEONCE_H_
#define SRC_CONTROLLER_AIRFORCEONCE_H_

//Air Force Once
#define AIRFORCEONE_BUTTON_ONE 1
#define AIRFORCEONE_BUTTON_TWO 2
#define AIRFORCEONE_BUTTON_THREE 3
#define AIRFORCEONE_BUTTON_FOUR 4
#define AIRFORCEONE_BUTTON_FIVE 5
#define AIRFORCEONE_BUTTON_SIX 6
#define AIRFORCEONE_BUTTON_SEVEN 7
#define AIRFORCEONE_BUTTON_EIGHT 8
#define AIRFORCEONE_BUTTON_NINE 9
#define AIRFORCEONE_X_AXIS 0
#define AIRFORCEONE_Y_AXIS 1
#define AIRFORCEONE_Z_AXIS 2

namespace Controller {

class Air_Force_Once {
public:
	Air_Force_Once();
	virtual ~Air_Force_Once();
};

} /* namespace Controller */

#endif /* SRC_CONTROLLER_AIRFORCEONCE_H_ */
